/*
 * This source file was generated by the Gradle 'init' task
 */

#include "lua-database-adapter.h"
#include <cassert>

int main() {
    lua_database_adapter::Greeter greeter;
    assert(greeter.greeting().compare("Hello, World!") == 0);
    return 0;
}
