/*
 * This source file was generated by the Gradle 'init' task
 */

#include <iostream>
#include <stdlib.h>
#include "lua-database-adapter.h"

std::string lua_database_adapter::Greeter::greeting() {
    return std::string("Hello, World!");
}
