/*
 * This source file was generated by the Gradle 'init' task
 */

#ifndef LUA_DATABASE_ADAPTER_H
#define LUA_DATABASE_ADAPTER_H

#ifdef _WIN32
#define LUA_DATABASE_ADAPTER_EXPORT_FUNC __declspec(dllexport)
#else
#define LUA_DATABASE_ADAPTER_EXPORT_FUNC
#endif

#include <string>

namespace lua_database_adapter {
    class Greeter {
        public:
        std::string LUA_DATABASE_ADAPTER_EXPORT_FUNC greeting();
    };
}

#endif
